openapi: 3.0.0
info:
  title: Nazri API
  version: 0.1.9

servers:
  - url: http://api.nazri.ir
    description: Main (production) server


paths:
  '/user/sign-up':
    post:
      tags:
        - user
      summary: sign up in Nazri
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                mobile_number:
                  type: string
                password:
                  type: string
              example:
                name: "John Doe"
                mobile_number: "09032567890"
                password: "qazwsx"
      responses:
        200:
          description: 'User created successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignUp'
        500:
          description: 'internal server error'

  '/user/sign-in':
    post:
      tags:
        - user
      summary: sign in in Nazri
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mobile_number:
                  type: string
                password:
                  type: string
              example:
                mobile_number: "09032567890"
                password: "qazwsx"
      responses:
        200:
          description: 'User created successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignIn'
        500:
          description: 'internal server error'

  '/user/get-users':
    get:
      tags:
        - user
      summary: sign in in Nazri
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mobile_number:
                  type: string
                password:
                  type: string
              example:
                mobile_number: "09032567890"
                password: "qazwsx"
      responses:
        200:
          description: 'User created successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsers'
        500:
          description: 'internal server error'


  '/reason/add':
    post:
      tags:
        - reason
      summary: add new reason
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
              example:
                reason: "اولین حقوق"
      responses:
        200:
          description: 'User created successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddReason'
        500:
          description: 'internal server error'


  '/reason/get':
    post:
      tags:
        - reason
      summary: get all reasons
      responses:
        200:
          description: 'Get reasons successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetReasons'
        500:
          description: 'internal server error'

  '/reason/delete':
    post:
      tags:
        - reason
      summary: delete a reason
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
              example:
                reason: 12
      responses:
        200:
          description: 'reason deleted successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteReason'
        500:
          description: 'internal server error'


components:
  schemas:
    SignUp:
      type: object
      properties:
        status:
          type: string
          example: "success"
        data:
          type: string
          example: "user created successfully."

    SignIn:
      type: object
      properties:
        status:
          type: string
          example: "success"
        data:
          type: object
          properties:
            token:
              type: string
              example: "Token kjsdjfsdfjuisdjnf232jklen124eij23n452"

    GetUsers:
      type: object
      properties:
        status:
          type: string
          example: "success"
        data:
          type: object
          properties:
            users:
              type: array
              example: [
                {
                  "id": 1,
                  "name": "John Doe",
                  "mobile_number": "09032567890",
                  "created_at": "2020-01-01 00:00:00",
                  "updated_at": "2020-01-01 00:00:00"
                },
                {
                  "id": 2,
                  "name": "John Doe",
                  "mobile_number": "09032567890",
                  "created_at": "2020-01-01 00:00:00",
                  "updated_at": "2020-01-01 00:00:00"
                }
              ]

    AddReason:
      type: object
      properties:
        status:
          type: string
          example: "success"
        data:
          type: object
          properties:
            reason:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                reason:
                  type: string
                  example: "اولین حقوق"
                create_at:
                    type: string
                    example: "2020-01-01 00:00:00"

    GetReasons:
      type: object
      properties:
        status:
          type: string
          example: "success"
        data:
          type: object
          properties:
            reasons:
              type: array
              example: [
                {
                  "id": 1,
                  "reason": "اولین حقوق",
                  "create_at": "2020-01-01 00:00:00"
                },
                {
                  "id": 2,
                  "reason": "اولین حقوق",
                  "create_at": "2020-01-01 00:00:00"
                }
              ]

    DeleteReason:
      type: object
      properties:
        status:
          type: string
          example: "success"
        data:
          type: string
          example: "reason 12 deleted"